version: "3.8"

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        container_name: node
        depends_on: 
            - mongo
        volumes:
            - /app/node_modules
            - ./:/app

    mongo:
        image: mongo
        restart : always
        environment : 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        ports: 
            - "27017:27017"
        volumes : 
            - my_data:/data/db
        
volumes:
    my_data:

        
