# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        echo "PORT=$PORT" >> .env
        echo "JWT_SECRET=$JWT_SECRET" >> .env
        echo "NODEMAILER_USER=$NODEMAILER_USER" >> .env
        echo "NODEMAILER_PASSWORD=$NODEMAILER_PASSWORD" >> .env
        npm install --prefix ./nodeServer
        npm run dev --prefix ./nodeServer
    env :  
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODEMAILER_USER: ${{ secrets.NODEMAILER_USER }}
      NODEMAILER_PASSWORD: ${{ secrets.NODEMAILER_PASSWORD }}
